name: Build and Deploy to Docker Hub and Redeploy DigitalOcean App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and tag Docker image with commit hash
    - name: Build and tag Docker image
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        echo "Using commit hash $COMMIT_HASH"
        docker build -t DOCKER_REPO:$COMMIT_HASH .
        docker tag DOCKER_REPO:$COMMIT_HASH DOCKER_REPO:latest

    # Step 4: Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push DOCKER_REPO:latest

    # Step 5: Trigger DigitalOcean redeployment
    - name: Trigger redeployment on DigitalOcean
      env:
        DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      run: |
        APP_ID=""
        curl -X POST "https://api.digitalocean.com/v2/apps/$APP_ID/deployments" \
        -H "Authorization: Bearer $DIGITALOCEAN_API_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"force_build": true}'
